foo: Hello from local
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8002/eureka/
    healthcheck:
      enabled: true
  instance:
    statusPageUrlPath: ${management.context-path}/info
    healthCheckUrlPath: ${management.context-path}/health